apiVersion: v1
kind: ConfigMap
metadata:
  name: pos-pricing-rules
  namespace: apparel-store
data:
  discountRules: |
    {
      "BlackFriday": {
        "enabled": true,
        "winter-coats": "55%",
        "boots": "50%", 
        "winter-jackets": "60%",
        "accessories": "40%",
        "surge-pricing": "active"
      }
    }
