apiVersion: apps/v1
kind: Deployment
metadata:
  name: pos-ui
  namespace: retail-pos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pos-ui
  template:
    metadata:
      labels:
        app: pos-ui
    spec:
      imagePullSecrets:
      - name: acr-secret
      containers:
      - name: pos-ui
        image: retailstorefrontacr.azurecr.io/react-pos:v4.4
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "250m"