apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment-pos.yaml
  - service-pos.yaml
  - configmap-pricing.yaml

commonLabels:
  app: pos-ui
  component: edge
  version: v1.0

namespace: retail-pos