apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-pos

resources:
  - ../../apps/edge/pos

patches:
  - path: pos-black-friday-patch.yaml
    target:
      kind: Deployment
      name: pos-ui

configMapGenerator:
  - name: pos-config
    literals:
      - STORE_LOCATION=New York
