apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-seattle-ingress
  namespace: retail-pos
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - seattle-pos.zavafashions-demo.com
    secretName: seattle-pos-tls
  rules:
  - host: seattle-pos.zavafashions-demo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pos-ui-service
            port:
              number: 80