apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pos-chicago-ingress
  namespace: retail-pos
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/redirect-scheme: "https"
    traefik.ingress.kubernetes.io/redirect-permanent: "true"
spec:
  ingressClassName: traefik
  tls:
  - hosts:
    - chicago-pos.zavafashions-demo.com
    secretName: chicago-pos-tls
  rules:
  - host: chicago-pos.zavafashions-demo.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: pos-ui-service
            port:
              number: 80