apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: retail-pos

resources:
  - ../../apps/edge/pos

patchesStrategicMerge:
  - pos-black-friday-patch.yaml

configMapGenerator:
  - name: pos-config
    literals:
      - STORE_LOCATION=Chicago
