apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: edge-chicago
  namespace: flux-system
spec:
  interval: 1m
  path: "./overlays/edge-chicago-black-friday"  # Switch to Black Friday overlay
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops-retail-demo
